# This is auto-generated by Datastar. DO NOT EDIT.
from enum import Enum


# TODO: Remove this and import builtin when python 3.10 support ends
class StrEnum(str, Enum):
    __str__ = str.__str__
    __format__ = str.__format__


# region Enums


# region The mode in which an element is patched into the DOM.
class ElementPatchMode(StrEnum):
    # Morphs the element into the existing element using Datastar's morphing, preserving focus and minimizing element changes.
    OUTER = "outer"

    # Morphs the element into the innerHTML using Datastar's morphing, preserving focus and minimizing element changes.
    INNER = "inner"

    # Removes the existing element from the DOM.
    REMOVE = "remove"

    # Prepends the element inside the existing element.
    PREPEND = "prepend"

    # Appends the element inside the existing element.
    APPEND = "append"

    # Inserts the element before the existing element.
    BEFORE = "before"

    # Inserts the element after the existing element.
    AFTER = "after"

    # Do not morph, simply replace the whole element and reset any related state.
    REPLACE = "replace"


# endregion ElementPatchMode


# region The type protocol on top of SSE which allows for core pushed based communication between the server and the client.
class EventType(StrEnum):
    # An event for patching HTML elements into the DOM.
    PATCH_ELEMENTS = "datastar-patch-elements"

    # An event for patching signals.
    PATCH_SIGNALS = "datastar-patch-signals"


# endregion EventType


# endregion Enums

DATASTAR_KEY = "datastar"
VERSION = "1.0.0-beta.11"

# region Default durations

# The default duration for retrying SSE on connection reset. This is part of the underlying retry mechanism of SSE.
DEFAULT_SSE_RETRY_DURATION = 1000

# endregion Default durations

# region Default strings


# endregion Default strings

# region Dataline literals
SELECTOR_DATALINE_LITERAL = "selector"
MODE_DATALINE_LITERAL = "mode"
ELEMENTS_DATALINE_LITERAL = "elements"
USE_VIEW_TRANSITION_DATALINE_LITERAL = "useViewTransition"
SIGNALS_DATALINE_LITERAL = "signals"
ONLY_IF_MISSING_DATALINE_LITERAL = "onlyIfMissing"
# endregion Dataline literals

# region Default booleans

# Should elements be patched using the ViewTransition API?
DEFAULT_ELEMENTS_USE_VIEW_TRANSITIONS = False

# Should a given set of signals patch if they are missing?
DEFAULT_PATCH_SIGNALS_ONLY_IF_MISSING = False

# endregion Default booleans