# This is auto-generated by Datastar. DO NOT EDIT.
from enum import Enum


# TODO: Remove this and import builtin when python 3.10 support ends
class StrEnum(str, Enum):
    __str__ = str.__str__
    __format__ = str.__format__


# region Enums


# region The mode in which an element is merged into the DOM.
class ElementMergeMode(StrEnum):
    # Morphs the element into the existing element using Datastar's morphing, preserving focus and minimizing element changes.
    OUTER = "outer"

    # Morphs the element into the innerHTML using Datastar's morphing, preserving focus and minimizing element changes.
    INNER = "inner"

    # Removes the existing element from the DOM.
    REMOVE = "remove"

    # Prepends the element inside the existing element.
    PREPEND = "prepend"

    # Appends the element inside the existing element.
    APPEND = "append"

    # Inserts the element before the existing element.
    BEFORE = "before"

    # Inserts the element after the existing element.
    AFTER = "after"


# endregion ElementMergeMode


# region The type protocol on top of SSE which allows for core pushed based communication between the server and the client.
class EventType(StrEnum):
    # An event for merging HTML elements into the DOM.
    MERGE_ELEMENTS = "datastar-merge-elements"

    # An event for merging signals.
    MERGE_SIGNALS = "datastar-merge-signals"

    # An event for executing <script/> elements in the browser.
    EXECUTE_SCRIPT = "datastar-execute-script"


# endregion EventType


# endregion Enums

DATASTAR_KEY = "datastar"
VERSION = "1.0.0-beta.11"

# region Default durations

# The default duration for retrying SSE on connection reset. This is part of the underlying retry mechanism of SSE.
DEFAULT_SSE_RETRY_DURATION = 1000

# endregion Default durations

# region Default strings

# The default attributes for <script/> element use when executing scripts. It is a set of key-value pairs delimited by a newline \\n character.
DEFAULT_EXECUTE_SCRIPT_ATTRIBUTES = "type module"

# endregion Default strings

# region Dataline literals
SELECTOR_DATALINE_LITERAL = "selector"
MERGE_MODE_DATALINE_LITERAL = "mergeMode"
ELEMENTS_DATALINE_LITERAL = "elements"
USE_VIEW_TRANSITION_DATALINE_LITERAL = "useViewTransition"
SIGNALS_DATALINE_LITERAL = "signals"
ONLY_IF_MISSING_DATALINE_LITERAL = "onlyIfMissing"
SCRIPT_DATALINE_LITERAL = "script"
ATTRIBUTES_DATALINE_LITERAL = "attributes"
AUTO_REMOVE_DATALINE_LITERAL = "autoRemove"
# endregion Dataline literals

# region Default booleans

# Should elements be merged using the ViewTransition API?
DEFAULT_ELEMENTS_USE_VIEW_TRANSITIONS = False

# Should a given set of signals merge if they are missing?
DEFAULT_MERGE_SIGNALS_ONLY_IF_MISSING = False

# Should script element remove itself after execution?
DEFAULT_EXECUTE_SCRIPT_AUTO_REMOVE = True

# endregion Default booleans